
# Model
gen_hidden_size: 512
gen_z_size: 5
#dis_emb_size: 256
#dis_hidden_1_size: 256
#dis_hidden_2_size: 256
#seg_loss_ratio: 0.5
#penalty_ratio: 10
#frame_temp: 0.9

# Data loader
dataset_size: 1000
phrase_length: 64
concat_window: 11
ascii_size: 256
batch_size: 7
num_workers: 0
#phn_max_length: 75
#feat_max_length: 777
#sample_var: 0.15
#repeat: 6
#
## Train
#batch_size: 50
#epoch: 2000 # for supervised training
#step: 10000 # for unsupervised training
#print_step: 100
#eval_step: 200
#gen_iter: 1
#dis_iter: 3
#gen_lr: 0.001
#dis_lr: 0.002
#sup_lr: 0.001



