
# Model
gen_hidden_size: 512
gen_z_size: 5
dis_emb_size: 256
dis_hidden_1_size: 256
dis_hidden_2_size: 256
gradient_penalty_ratio: 10
#frame_temp: 0.9

# Data loader
dataset_size: 1000
replace_with_noise_probability: 0.0
phrase_length: 60
concat_window: 11
ascii_size: 256
num_workers: 4

## Train
num_epochs: 1000
batch_size: 50
learning_rate: 0.001
eval_epoch_every: 1


