
# Model
gen_hidden_size: 512
gen_z_size: 1
dis_emb_size: 256
dis_hidden_1_size: 256
dis_hidden_2_size: 256
gradient_penalty_ratio: 10.0
#frame_temp: 0.9

# Data loader
dataset_size: 4800
replace_with_noise_probability: 0.0
phrase_length: 60
concat_window: 5
ascii_size: 256

num_workers: 8
## Train
steps: 1000
eval_step: 100
print_step: 20

batch_size: 50

gen_learning_rate: 0.001
dis_learning_rate: 0.002
gen_iter: 1
dis_iter: 3

